### ISSUE TITLE
Group by (or filter by) formulae that are not dependencies of another package

### ISSUE THREAD

**Issue by wesley-maney** [buresdv/Cork#247] opened 2023-12-10 15:34 UTC
# Feature Suggestion

## Mandatory Information
**Description**
The ability to group formulae in the sidebar into 2 sections: "Direct formulae installed" and "Dependencies". Or: the ability to filter to only show direct formulae in the sidebar.

_Why?_
When cleaning my homebrew stack and checking for formulae I no longer need (old projects etc.) I'd love a view to quickly see which formulae I have decided to install (ones where I deliberately typed `brew install` for). That way, I can quickly remove these and have all their dependents removed automatically as well.

What's already great about Cork is that when clicking on a formula, it will show inside a pill that it's a dependency of other packages.
So at the moment, I just keep going down the list slowly until I see a package with no pill attached to it and I know that it's a package I have installed directly.

But it'd save a lot of time to be able to see all of those formulae directly in some way.

**Type**
UI-Improvement.

**Mockups**
(A quickly made example)
![Frame 5](https://github.com/buresdv/Cork/assets/13488705/60c4d821-80d8-4d76-8b91-af6b03fa85fd)

## Checklist
- [x] I have filled out everything under **Mandatory Information**

**Comment by buresdv** [comment] 2023-12-10 21:36
I may be misunderstanding, but I believe this is what the "Show only manually installed packages" option does. It hides all the packages that were installed as depencies only, and shows only the packages that you manually installed.

There's also a search filter for that, but due to a bug caused by Apple, it's currently inaccessible (#191). So for now, that setting is the only way to filter out all dependencies

**Comment by buresdv** [comment] 2023-12-16 10:11
Closing

**Closed by buresdv** 2023-12-16 10:11 UTC
Labels: Enhancement
