### ISSUE TITLE
"not authorized to read cache" when using Tuist to generate

### ISSUE THREAD

**Issue by RWCoding58** [buresdv/Cork#371] opened 2024-08-01 04:02 UTC
# Bug Report

## Mandatory Information
**Describe the bug**
I haven't used my Macbook in a while (close to two months), so I decided to upgrade Cork once I got to use it. Apparently, the method to compile Cork has changed, but now when I run `tuist generate`, I get `(username) is not authorized to read cache`. I'm not sure if I was not supposed to log in with my own account, since I had been prompted to authenticate with `tuist auth` before this and created a new account.

**To Reproduce**
1. Run the compilation command (`git clone https://github.com/buresdv/Cork.git && cd Cork && tuist install && tuist generate`)
2. Most of the steps work correctly
3. Once it reaches the `tuist generate` step, it produces an error as follows:
```
Loading and constructing the graph
It might take a while if the cache is empty
Fetching remote binaries. Hold tight...
(my username) is not authorized to read cache
Consider creating an issue using the following link: https://github.com/tuist/tuist/issues/new/choose
```

**Expected Behavior**
The Xcode project generates and opens in Xcode.

**System and Cork Information:**
 - macOS version: 14.4.1 (23E224)
 - Cork Version: 1.4.2 (62)
 - Did you compile Cork yourself?: Yes

## Optional Information

**Additional context**
As mentioned at the start, I haven't used my Mac in a while so my version of Cork is very outdated (along with my other apps).

# Checklist
- [x] I filled everything out under **Mandatory Information**

**Comment by buresdv** [comment] 2024-08-01 10:01
I updated the readme. Can you try the new instructions? It may be fixed, but I'm not sure

**Comment by RWCoding58** [comment] 2024-08-01 10:02
I'll try it when I get back soon (in about an hour). Thanks for the fast reply!

**Comment by RWCoding58** [comment] 2024-08-01 10:54
Yep, the app generates properly now and I can compile it. However, it seems the app shows the "Thank you for trying out Cork" trial window even though I had selected "Self-Compiled" in Xcode before building.

**Comment by buresdv** [comment] 2024-08-01 21:09
I'm happy to hear it works. Unfortunately, we can't reproduce your problem:

![Snímek obrazovky 2024-08-01 v 23 06 21](https://github.com/user-attachments/assets/a7ef5323-cd62-4ad4-b16c-be1f70798ac7)

I'd say, make sure that you have actually selected the right scheme in the toolbar, or try to do a fresh build by using the command `tuist clean`, then going through the instructions again.

Because the original problem got solved, I'll be closing this issue.

**Closed by buresdv** 2024-08-01 21:09 UTC
Labels: Bug

**Comment by RWCoding58** [comment] 2024-08-02 00:45
Alright, I'll give it a try. I think it might be because I installed over my old app which had also shown the trial error.
