### ISSUE TITLE
Package resolution errors

### ISSUE THREAD

**Issue by smuemd** [buresdv/Cork#297] opened 2024-04-02 06:50 UTC
On following the "Compiling Cork" instruction in [README.md](https://github.com/buresdv/Cork?tab=readme-ov-file#compiling-cork) I get error messages when attempting to build from source (`Product → Archive`) in Xcode. Appears to be related to #296 

**Screenshots**
<img width="823" alt="image" src="https://github.com/buresdv/Cork/assets/3016582/4444f07c-792b-45fd-aa43-1a04d6b5ac21">

macOS version: 14.2.1 (23C71)
Xcode Version 15.3 (15E204a)

**Comment by buresdv** [comment] 2024-04-02 10:54
Hey, this is a duplicate of #296, let's discuss that there

**Closed by buresdv** 2024-04-02 10:54 UTC
Labels: Bug
