### ISSUE TITLE
Failed to Resolve

### ISSUE THREAD

**Issue by njthebaud** [buresdv/Cork#296] opened 2024-04-01 23:06 UTC
Hi,

I've never done a build before but am following all the steps. I added my developer account but after cloning the repo I get failed to resolve (see attached).
![SCR-20240401-qosj](https://github.com/buresdv/Cork/assets/163397722/48c15ceb-a996-42c4-8caa-0746041caf16)

**Comment by njthebaud** [comment] 2024-04-02 00:00
I think my free developer's account is currently pending, which is what's maybe causing the issue.

**Comment by buresdv** [comment] 2024-04-02 11:01
I can't reproduce this, but I updated some code since you submitted this issue. Can you try again with the current state of `main`?

**Comment by njthebaud** [comment] 2024-04-02 11:21
ok it seems to work now although I still got 11 issues (see attached). The app opens and runs fine, but I did have to select the 7 day trial in order to actually access anything. Is that how it's suppose to be or will I be locked out after 7 days?

![image](https://github.com/buresdv/Cork/assets/163397722/b219a2e9-8aec-4734-88c7-245f0e2c4339)

**Comment by njthebaud** [comment] 2024-04-02 11:23
ok it seems to work now although I still got 11 issues (see attached). The app opens and runs fine, but I did have to select the 7 day trial in order to actually access anything. Is that how it's suppose to be or will I be locked out after 7 days?

![image](https://github.com/buresdv/Cork/assets/163397722/ccf690bf-7231-48d0-b6d8-d76f4201eaf5)

**Comment by buresdv** [comment] 2024-04-02 11:28
Currently, there's a lot of work being done on the licensing system, and it's not finished. It's recommended that you build a version marked by a version tag (although it's not explicitly specified in the readme, which I'll fix). If you don't want to wait until it's fully implemented and want to bypass that trial now, go to this line:
https://github.com/buresdv/Cork/blob/f0d0411619ccc53374b2a7d9f63fa59a65ac30dc/Cork/CorkApp.swift#L96
And add this code to the line just above it:
`hasValidatedEmail = true`

I'll close this issue for now, as the original problem is solved.

**Closed by buresdv** 2024-04-02 11:28 UTC

**Comment by njthebaud** [comment] 2024-04-02 13:11
Thank you! Appreciate all the help ;)
