### ISSUE TITLE
Cork hangs when search result is big with package descriptions

### ISSUE THREAD

**Issue by kondayutarou** [buresdv/Cork#391] opened 2024-08-25 07:37 UTC
### What were you trying to do?

1. Check "Show package descriptions"
2. Search "a"
3. Keep scrolling

### What was the problem?

The app starts to hang occasionally and Mac freezes

Here's a TimeProfiler log
<img width="1432" alt="image" src="https://github.com/user-attachments/assets/d9ecc89f-4ac7-491a-b9d3-9504c335ab5f">

I couldn't record well due to the hang.
https://github.com/user-attachments/assets/43d8319a-eada-4de3-93e9-d93993d5047d

### App Version

1.4.4.2

### App Acquisition

Self-Compiled

### Final checklist

- [X] This report is about the interface, and I included screenshots of the problem

**Comment by buresdv** [comment] 2024-08-25 17:49
Thanks for the report. This is a duplicate of #168

**Closed by buresdv** 2024-08-25 17:49 UTC
Labels: Bug
